# Generated by Django 2.1.2 on 2018-11-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('weight', models.CharField(max_length=20, verbose_name='重量')),
                ('size', models.CharField(max_length=20, verbose_name='尺寸')),
                ('type', models.CharField(max_length=20, verbose_name='产品类型')),
            ],
        ),
    ]
