# Generated by Django 2.1.2 on 2018-11-22 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('masterpiece', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Performer_info',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('birth', models.CharField(max_length=20)),
                ('elapse', models.CharField(max_length=20)),
                ('performer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='viewthis.Performer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('weight', models.CharField(max_length=20, verbose_name='重量')),
                ('size', models.CharField(max_length=20, verbose_name='尺寸')),
            ],
            options={
                'verbose_name': '产品信息',
                'verbose_name_plural': '产品信息',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewthis.Performer')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramAnother',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('performer', models.ManyToManyField(to='viewthis.Performer')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('type_name', models.CharField(max_length=20, verbose_name='产品类型')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewthis.Type'),
        ),
    ]
