# Generated by Django 2.1.2 on 2018-11-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewthis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('visit_product', 'Can visit Product'),), 'verbose_name': '产品信息', 'verbose_name_plural': '产品信息'},
        ),
    ]
